version: '3.9'
services:
  #postgresql database
  postgres:
    image: postgres
    container_name: postgresdb
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=eshopdb
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eshop.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
  #category-service microservice
  category-service:
    build: ./category-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PRODUCT_SERVICE_URL=http://product-service:8080
    ports:
      - "8000:8080"
    depends_on:
      - postgres
  #product-service microservice
  product-service:
    build: ./product-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8001:8080"
    depends_on:
      - postgres
  #apache-proxy
  apache:
    build: ./apache-proxy
    ports:
      - "8080:80"

volumes:
  postgres: {}
  pgadmin: {}