apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresdb
spec:
  serviceName: postgresdb
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: docker.io/postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: eshopdb
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---

# accessible hat http://localhost:5050 with 'kubectl port-forward deployment/pgadmin 5050:80'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: docker.io/dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@eshop.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
          volumeMounts:
            - name: config-volume
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
      volumes:
        - name: config-volume
          configMap:
            name: pgadmin-config

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-service
  template:
    metadata:
      labels:
        app: category-service
    spec:
      containers:
        - name: category-service
          image: docker.io/maxoe1998/category-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: docker.io/maxoe1998/product-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-shop-db-image
spec:
  serviceName: web-shop-db-image
  replicas: 1
  selector:
    matchLabels:
      app: web-shop-db-image
  template:
    metadata:
      labels:
        app: web-shop-db-image
    spec:
      containers:
        - name: web-shop-db-image
          image: mavogel/hska-vis-web-shop-db-image:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: c8de110f37300a53a971749
            - name: MYSQL_DATABASE
              value: webshop
            - name: MYSQL_USER
              value: webshopuser
            - name: MYSQL_PASSWORD
              value: 240b2c6d58ff2ce2f508b49f
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---

# accessible hat http://localhost:6060 with 'kubectl port-forward deployment/phpmyadmin 6060:80'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: docker.io/phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: web-shop-db-image
            - name: PMA_USER
              value: webshopuser
            - name: PMA_PASSWORD
              value: 240b2c6d58ff2ce2f508b49f
            - name: PMA_DBNAME
              value: webshop

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacywebshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacywebshop
  template:
    metadata:
      labels:
        app: legacywebshop
    spec:
      containers:
        - name: legacywebshop
          image: mavogel/hska-vis-legacywebshop:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: postgresdb
spec:
  selector:
    app: postgresdb
  ports:
    - protocol: TCP
      port: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: category-service
spec:
  selector:
    app: category-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: web-shop-db-image
spec:
  selector:
    app: web-shop-db-image
  ports:
    - protocol: TCP
      port: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: legacywebshop
spec:
  selector:
    app: legacywebshop
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  servers.json: |-
    {
      "Servers": {
        "1": {
          "Name": "WebshopDB",
          "Group": "Servers",
          "Host": "postgresdb",
          "Port": 5432,
          "SSLMode": "prefer",
          "MaintenanceDB": "postgres",
          "Username": "admin",
          "PassFile": "",
          "SSLCompression": 0,
          "SSLInsecureRenegotiation": 0,
          "SSLCert": "",
          "SSLCipher": "",
          "KeyFile": "",
          "SSLRootCert": "",
          "SSLCrl": "",
          "SSLCompression": 0,
          "Timeout": 10,
          "ApplicationName": "pgAdmin 4 - default"
        }
      }
    }