# In a real project, this file should be added to .gitignore to hide secrets.
# Write (from root path) 'kubectl apply -f ./k8s-config/secret/secret.yaml'
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
type: Opaque
stringData:
  #MYSQL base-64 encoded
  mysql_root_password: c8de110f37300a53a971749
  mysql_password: 240b2c6d58ff2ce2f508b49f
  #PHPMYADMIN
  pma_password: 240b2c6d58ff2ce2f508b49f
  #POSTGRES
  postgres_password: admin
  #PGADMIN
  pgadmin_default_password: admin
