apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-shop-db-image
spec:
  serviceName: web-shop-db-image
  replicas: 1
  selector:
    matchLabels:
      app: web-shop-db-image
  template:
    metadata:
      labels:
        app: web-shop-db-image
    spec:
      containers:
        - name: web-shop-db-image
          image: mavogel/hska-vis-web-shop-db-image:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: c8de110f37300a53a971749
            - name: MYSQL_DATABASE
              value: webshop
            - name: MYSQL_USER
              value: webshopuser
            - name: MYSQL_PASSWORD
              value: 240b2c6d58ff2ce2f508b49f
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---

# accessible hat http://localhost:6060 with 'kubectl port-forward deployment/phpmyadmin 6060:80'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: docker.io/phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: web-shop-db-image
            - name: PMA_USER
              value: webshopuser
            - name: PMA_PASSWORD
              value: 240b2c6d58ff2ce2f508b49f
            - name: PMA_DBNAME
              value: webshop

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacywebshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacywebshop
  template:
    metadata:
      labels:
        app: legacywebshop
    spec:
      containers:
        - name: legacywebshop
          image: mavogel/hska-vis-legacywebshop:latest
          ports:
            - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: web-shop-db-image
spec:
  selector:
    app: web-shop-db-image
  ports:
    - protocol: TCP
      port: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: legacywebshop
spec:
  selector:
    app: legacywebshop
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8080