apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-depl
spec:
  selector:
    matchLabels:
      app: reverse-proxy-depl
  template:
    metadata:
      labels:
        app: reverse-proxy-depl
    spec:
      containers:
        - name: reverse-proxy-depl
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config

---

apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-svc
spec:
  selector:
    app: reverse-proxy-depl
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    events { }

    http {
      server {
        listen 80;

        location /dashboard/pgadmin/ {
          proxy_pass http://pgadmin:5050/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Script-Name /dashboard/pgadmin;
          proxy_redirect ~^(http://[^:]+):\d+(.*)$ $scheme://$host/dashboard/pgadmin$2;
        }

        location /dashboard/phpmyadmin/ {
          proxy_pass http://phpmyadmin:6060/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_redirect ~^(http://[^:]+):\d+(.*)$ $scheme://$host/dashboard/phpmyadmin$2;
        }
      }
    }