apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: bitnami/apache:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: reverse-proxy-config
              mountPath: /usr/local/apache2/conf/httpd.conf
              subPath: httpd.conf
      volumes:
        - name: reverse-proxy-config
          configMap:
            name: reverse-proxy-config


---

# accessible with 'kubectl port-forward svc/reverse-proxy-svc 80:80'
#  - http://localhost/dashboard/phpmyadmin/
#  - http://localhost/dashboard/pgadmin
#  - http://localhost/api/v1/product
#  - http://localhost/api/v1/category
#  - http://localhost/swagger/product
#  - http://localhost/swagger/category
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  selector:
    app: reverse-proxy
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: reverse-proxy-config
data:
  httpd.conf: |-
    <VirtualHost *:80>
        ServerName localhost

        ErrorLog /dev/stderr
        CustomLog /dev/stdout combined

        ProxyPreserveHost On

        ProxyPass         /dashboard/pgadmin http://pgadmin:5050/
        ProxyPassReverse  /dashboard/pgadmin http://pgadmin:5050/

        ProxyPass         /dashboard/phpmyadmin http://phpmyadmin:6060/
        ProxyPassReverse  /dashboard/phpmyadmin http://phpmyadmin:6060/

        ProxyPass         /api/v1/product http://product-service:8001/v1/products
        ProxyPassReverse  /api/v1/product http://product-service:8001/v1/products

        ProxyPass         /api/v1/category http://category-service:8000/v1/categories
        ProxyPassReverse  /api/v1/category http://category-service:8000/v1/categories

        ProxyPass         /swagger/product http://product-service:8001/swagger-ui/index.html
        ProxyPassReverse  /swagger/product http://product-service:8001/swagger-ui/index.html

        ProxyPass         /swagger/category http://category-service:8000/swagger-ui/index.html
        ProxyPassReverse  /swagger/category http://category-service:8000/swagger-ui/index.html
    </VirtualHost>
