# accessible at http://localhost:5050 with 'kubectl port-forward deployment/pgadmin 5050:80'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: pgadmin
          image: docker.io/dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@eshop.com
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: pgadmin_default_password
          volumeMounts:
            - name: pgadmin-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
      volumes:
        - name: pgadmin-config
          configMap:
            name: pgadmin-config

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-service
  template:
    metadata:
      labels:
        app: category-service
    spec:
      containers:
        - name: category-service
          image: docker.io/dnszlr/category-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:8080
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: docker.io/dnszlr/product-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: CATEGORY_SERVICE_URL
              value: http://category-service:8080
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: LoadBalancer
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  name: category-service
spec:
  type: LoadBalancer
  selector:
    app: category-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
status:
  loadBalancer: {}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  servers.json: |-
    {
      "Servers": {
        "1": {
          "Name": "WebshopDB",
          "Group": "Servers",
          "Host": "postgresdb",
          "Port": 5432,
          "SSLMode": "prefer",
          "MaintenanceDB": "postgres",
          "Username": "admin",
          "PassFile": "",
          "SSLCompression": 0,
          "SSLInsecureRenegotiation": 0,
          "SSLCert": "",
          "SSLCipher": "",
          "KeyFile": "",
          "SSLRootCert": "",
          "SSLCrl": "",
          "SSLCompression": 0,
          "Timeout": 10,
          "ApplicationName": "pgAdmin 4 - default"
        }
      }
    }