name: Java CI with Gradle

on:
  push:
    branches:
      - master
    paths:
      - 'category-service/**'
      - 'product-service/**'
  pull_request:
    branches:
      - master
    paths:
      - 'category-service/**'
      - 'product-service/**'
  workflow_dispatch: # Enable manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Run tests with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: '7.2'
        tasks: 'test --info'
